environment:
  VSCODE_BUILD_VERBOSE: true

install:
  - ps: Install-Product node
  - npm install -g npm --silent

build_script:
  - npm install
  - npm run vscode:prepublish

test_script:
  - npm test --silent