language: node_js
node_js:
- '10'
os:
  - osx
before_install:
  - npm install -g typescript
install:
 - npm install
script:
  - npm run compile
  - npm test
notifications:
  email:
    on_success: change